Bookmarks undo deletion
duckduckgo/macos-browser pull request #3327
Opened 2024-09-23 06:00 UTC by mallexxx

Task/Issue URL: https://app.asana.com/0/1202406491309510/1205306631184883/f

**Description**:
- Undoing bookmarks removal using Cmd+Z

**Steps to test this PR**:
1. Select a bookmark(s) and folder(s) in the Bookmark Manager/Bookmarks Popup/Bookmarks Bar, remove; hit Cmd+z - validate the entities are restored at initial positions
2. Hit Cmd+Shift+Z to redo removal
3. Activate the Address Bar - validate undo is cleared; Activate another tab - validate undo is cleared

**Definition of Done**:

* [ ] Does this PR satisfy our [Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f)?

---
###### Internal references:
[Pull Request Review Checklist](https://app.asana.com/0/1202500774821704/1203764234894239/f)
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/1204012835277482/f)

2024-10-15 12:34 UTC, ayoy requested changes
@mallexxx this is working great, amazing job as always! 🎉 

I've only found that when undoing favorites deletion, we're not putting them back at the original index in favorites array. See the comment inline. It won't be trivial, but also shouldn't be terribly much work. Let me know what you think. cc @jotaemepereira

2024-10-15 12:34 UTC, ayoy commented on UnitTests/Bookmarks/Model/LocalBookmarkManagerTests.swift
> +private typealias BookmarksBuilder = ArrayBuilder<BookmarksBuilderItem>
I realize that this builder works on `BaseBookmarkEntity` type and I appreciate you adding it, but just wanted to remind and check if you remembered that we have `BookmarkTreeBuilder` in BSK that works on `BookmarkEntity` (managed object class) and could have perhaps be reused here. I understand if it couldn't 👍

2024-10-17 17:34 UTC, jotaemepereira commented on DuckDuckGo/Bookmarks/Model/BookmarkManager.swift
> +    case bookmark(url: String, title: String, isFavorite: Bool, parent: KnownBookmarkFolderIdList?, index: Int?)
Thanks @ayoy . This was fixed and merged to this branch.

2024-10-18 15:03 UTC, ayoy approved these changes
🚀  thanks a lot @jotaemepereira!

2024-10-18 19:38 UTC, merged