Implement tab bar remote message
duckduckgo/macos-browser pull request #3665
Opened 2024-12-12 21:01 UTC by jotaemepereira

Task/Issue URL: https://app.asana.com/0/1204006570077678/1208963049725240/f
Tech Design URL: 
CC:

**Description**
Adds a new remote message that is shown in the tab bar.

**Steps to test this PR**:
1. Go to the `RemoteMessagingClient` and change the DEBUG endpoint URL to `https://www.jsonblob.com/api/1316017217598578688`
2. Run the app
3. You should see the new blue button in the tab bar
4. When hovering it, it should show a popup.
5. Tapping the button will take you to the survey
6. Test that when the button is dismissed is removed in all windows
7. Test that New Tab Page does not show this new message

<!—
Tagging instructions
If this PR isn't ready to be merged for whatever reason it should be marked with the `DO NOT MERGE` label (particularly if it's a draft)
If it's pending Product Review/PFR, please add the `Pending Product Review` label.

If at any point it isn't actively being worked on/ready for review/otherwise moving forward (besides the above PR/PFR exception) strongly consider closing it (or not opening it in the first place). If you decide not to close it, make sure it's labelled to make it clear the PRs state and comment with more information.
—>

**Definition of Done**:

* [ ] Does this PR satisfy our [Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f)?

—
###### Internal references:
[Pull Request Review Checklist](https://app.asana.com/0/1202500774821704/1203764234894239/f)
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/1204012835277482/f)

2024-12-17 22:04 UTC, ayoy requested changes
Hey @jotaemepereira! The message works nicely but l've found a bug in HTML NTP and also wanted to suggest some changes in the view to better support localization. Please have a look, thanks!

2024-12-17 22:04 UTC, ayoy commented on DuckDuckGo/TabBar/View/TabBarRemoteMessagePresenting.swift
> +            self.showTabBarRemotePopup(message)
Same here with weak self

2024-12-19 14:52 UTC, jotaemepereira commented on DuckDuckGo/RemoteMessaging/TabBarRemoteMessageView.swift
> +            .frame(width: 147)
This was fixed. Now, both the button and the popover will resize accordingly.

2024-12-19 14:52 UTC, jotaemepereira commented on DuckDuckGo/RemoteMessaging/TabBarRemoteMessageView.swift
> +    @State private var presentPopup: Bool = false
I removed it.

2024-12-19 14:53 UTC, jotaemepereira commented on DuckDuckGo/RemoteMessaging/TabBarRemoteMessageView.swift
> +    }
This was fixed, now we do not have fixed a fixed height for the popover, the popover will increase in height in case it spans more lines.

2024-12-19 14:53 UTC, jotaemepereira commented on DuckDuckGo/RemoteMessaging/TabBarRemoteMessageView.swift
> +            .padding(.horizontal, 7.5)
I removed this button style.

2024-12-19 15:20 UTC, jotaemepereira commented on DuckDuckGo/RemoteMessaging/TabBarRemoteMessageView.swift
> +            .onAppear(perform: { onAppear() })
This button style was removed.

2024-12-19 18:44 UTC, jotaemepereira commented on DuckDuckGo/NewTabPage/ActiveRemoteMessageModel+NewTabPage.swift
> +            .filter { $0?.isForTabBar == false }
Done 👍🏼

2024-12-19 19:10 UTC, jotaemepereira commented on DuckDuckGo/RemoteMessaging/RemoteMessagingClient.swift
> +            URL(string: "https://www.jsonblob.com/api/1316017217598578688")!
⚠️ This shouldn’t be merged; after approval, I will revert this file to the original URLs.

2024-12-19 19:10 UTC, jotaemepereira commented on DuckDuckGo/RemoteMessaging/TabBarRemoteMessageView.swift
> +        .frame(width: 360)
Now, we only fix the width of the popover; if the text is larger, the popover should increase its height.

2025-01-02 10:47 UTC, ayoy approved these changes
All looks and works great now :) 🎉  thanks a lot @jotaemepereira and sorry to keep you waiting so long 😬 

I added a tiny change that updates the publisher name in NewTabPageActiveRemoteMessageProviding.

2025-01-02 10:47 UTC, ayoy commented on tab-bar-remote-message.json
Also remember to remove this file :)

2025-01-03 19:41 UTC, merged